/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as RegrasRouteImport } from './routes/regras'
import { Route as RankingRouteImport } from './routes/ranking'
import { Route as ParticiparRouteImport } from './routes/participar'
import { Route as PalpitesRouteImport } from './routes/palpites'
import { Route as LiderRouteImport } from './routes/lider'
import { Route as JogosRouteImport } from './routes/jogos'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as JogosMatchIdRouteImport } from './routes/jogos_.$matchId'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const RegrasRoute = RegrasRouteImport.update({
  id: '/regras',
  path: '/regras',
  getParentRoute: () => rootRouteImport,
} as any)
const RankingRoute = RankingRouteImport.update({
  id: '/ranking',
  path: '/ranking',
  getParentRoute: () => rootRouteImport,
} as any)
const ParticiparRoute = ParticiparRouteImport.update({
  id: '/participar',
  path: '/participar',
  getParentRoute: () => rootRouteImport,
} as any)
const PalpitesRoute = PalpitesRouteImport.update({
  id: '/palpites',
  path: '/palpites',
  getParentRoute: () => rootRouteImport,
} as any)
const LiderRoute = LiderRouteImport.update({
  id: '/lider',
  path: '/lider',
  getParentRoute: () => rootRouteImport,
} as any)
const JogosRoute = JogosRouteImport.update({
  id: '/jogos',
  path: '/jogos',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const JogosMatchIdRoute = JogosMatchIdRouteImport.update({
  id: '/jogos_/$matchId',
  path: '/jogos/$matchId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/jogos': typeof JogosRoute
  '/lider': typeof LiderRoute
  '/palpites': typeof PalpitesRoute
  '/participar': typeof ParticiparRoute
  '/ranking': typeof RankingRoute
  '/regras': typeof RegrasRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/jogos/$matchId': typeof JogosMatchIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/jogos': typeof JogosRoute
  '/lider': typeof LiderRoute
  '/palpites': typeof PalpitesRoute
  '/participar': typeof ParticiparRoute
  '/ranking': typeof RankingRoute
  '/regras': typeof RegrasRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/jogos/$matchId': typeof JogosMatchIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/jogos': typeof JogosRoute
  '/lider': typeof LiderRoute
  '/palpites': typeof PalpitesRoute
  '/participar': typeof ParticiparRoute
  '/ranking': typeof RankingRoute
  '/regras': typeof RegrasRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/jogos_/$matchId': typeof JogosMatchIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/jogos'
    | '/lider'
    | '/palpites'
    | '/participar'
    | '/ranking'
    | '/regras'
    | '/sitemap.xml'
    | '/jogos/$matchId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/jogos'
    | '/lider'
    | '/palpites'
    | '/participar'
    | '/ranking'
    | '/regras'
    | '/sitemap.xml'
    | '/jogos/$matchId'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/jogos'
    | '/lider'
    | '/palpites'
    | '/participar'
    | '/ranking'
    | '/regras'
    | '/sitemap.xml'
    | '/jogos_/$matchId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  JogosRoute: typeof JogosRoute
  LiderRoute: typeof LiderRoute
  PalpitesRoute: typeof PalpitesRoute
  ParticiparRoute: typeof ParticiparRoute
  RankingRoute: typeof RankingRoute
  RegrasRoute: typeof RegrasRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  JogosMatchIdRoute: typeof JogosMatchIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/regras': {
      id: '/regras'
      path: '/regras'
      fullPath: '/regras'
      preLoaderRoute: typeof RegrasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ranking': {
      id: '/ranking'
      path: '/ranking'
      fullPath: '/ranking'
      preLoaderRoute: typeof RankingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/participar': {
      id: '/participar'
      path: '/participar'
      fullPath: '/participar'
      preLoaderRoute: typeof ParticiparRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/palpites': {
      id: '/palpites'
      path: '/palpites'
      fullPath: '/palpites'
      preLoaderRoute: typeof PalpitesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lider': {
      id: '/lider'
      path: '/lider'
      fullPath: '/lider'
      preLoaderRoute: typeof LiderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/jogos': {
      id: '/jogos'
      path: '/jogos'
      fullPath: '/jogos'
      preLoaderRoute: typeof JogosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/jogos_/$matchId': {
      id: '/jogos_/$matchId'
      path: '/jogos/$matchId'
      fullPath: '/jogos/$matchId'
      preLoaderRoute: typeof JogosMatchIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  JogosRoute: JogosRoute,
  LiderRoute: LiderRoute,
  PalpitesRoute: PalpitesRoute,
  ParticiparRoute: ParticiparRoute,
  RankingRoute: RankingRoute,
  RegrasRoute: RegrasRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  JogosMatchIdRoute: JogosMatchIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
